"""empty message

Revision ID: 663e73fb4391
Revises: 
Create Date: 2018-07-23 11:45:26.044130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663e73fb4391'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike')
    # ### end Alembic commands ###
